// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNUnFeYVFDI6kCMOhdwT1AXwQVFDEswJM',
    appId: '1:210562490075:web:8c1a6d14ea24becb08f6fe',
    messagingSenderId: '210562490075',
    projectId: 'pikturesque',
    authDomain: 'pikturesque.firebaseapp.com',
    storageBucket: 'pikturesque.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYuPkknr46_J4WWW408-K8ERh08vNOBI4',
    appId: '1:210562490075:android:ada29e18ec49416f08f6fe',
    messagingSenderId: '210562490075',
    projectId: 'pikturesque',
    storageBucket: 'pikturesque.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL7sdfVaPNbFniXQ9r9mws-90xgBO118c',
    appId: '1:210562490075:ios:21fd6a39226429c908f6fe',
    messagingSenderId: '210562490075',
    projectId: 'pikturesque',
    storageBucket: 'pikturesque.appspot.com',
    iosClientId: '210562490075-pp6pahq53iopkbj7pe1is9da1kipa239.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaApp',
  );
}
